In [1]:
import numpy as np
from utils import datasets

In [2]:
def analyze(dataset):
    imbalance = None
    if dataset == 'digits':
        imbalance = datasets.HIGH_IMBALANCE_AMOUNTS_DIGITS_DIFFERENT_PY
    elif dataset == 'domainnet':
        imbalance = datasets.IMBALANCE_AMOUNTS_DOMAINNET_DIFFERENT_PY
    x_train, x_test, y_train, y_test, classes = datasets.load(dataset, imbalance=imbalance)
    domains = x_train.keys()
    for domain in domains:
        print(domain, 'train', x_train[domain].shape)
        classes, counts = np.unique(y_train[domain], return_counts=True)
        print(classes, counts, counts / sum(counts))
        print(domain, 'test', x_test[domain].shape)
        classes, counts = np.unique(y_test[domain], return_counts=True)
        print(classes, counts, counts / sum(counts))
        print()

In [3]:
analyze('digits')

mnist train (2370, 3, 28, 28)
[0 1 2 3 4 5 6 7 8 9] [500 500 500 500 200 100  40  10  10  10] [0.21097046 0.21097046 0.21097046 0.21097046 0.08438819 0.04219409
 0.01687764 0.00421941 0.00421941 0.00421941]
mnist test (10000, 3, 28, 28)
[0 1 2 3 4 5 6 7 8 9] [ 980 1135 1032 1010  982  892  958 1028  974 1009] [0.098  0.1135 0.1032 0.101  0.0982 0.0892 0.0958 0.1028 0.0974 0.1009]

mnistm train (2370, 3, 28, 28)
[0 1 2 3 4 5 6 7 8 9] [ 10 200 100 500  40 500  10 500 500  10] [0.00421941 0.08438819 0.04219409 0.21097046 0.01687764 0.21097046
 0.00421941 0.21097046 0.21097046 0.00421941]
mnistm test (10000, 3, 28, 28)
[0 1 2 3 4 5 6 7 8 9] [ 980 1135 1032 1010  982  892  958 1028  974 1009] [0.098  0.1135 0.1032 0.101  0.0982 0.0892 0.0958 0.1028 0.0974 0.1009]

svhn train (2370, 3, 32, 32)
[0 1 2 3 4 5 6 7 8 9] [200  10  10 500 500 100  40  10 500 500] [0.08438819 0.00421941 0.00421941 0.21097046 0.21097046 0.04219409
 0.01687764 0.00421941 0.21097046 0.21097046]
svhn test (26032, 3, 32,

In [4]:
analyze('domainnet')

clipart train (900, 3, 32, 32)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16] [120 120 120 120  80  60  60  40  40  25  25  25  25  10  10  10  10] [0.13333333 0.13333333 0.13333333 0.13333333 0.08888889 0.06666667
 0.06666667 0.04444444 0.04444444 0.02777778 0.02777778 0.02777778
 0.02777778 0.01111111 0.01111111 0.01111111 0.01111111]
clipart test (1020, 3, 32, 32)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16] [60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60] [0.05882353 0.05882353 0.05882353 0.05882353 0.05882353 0.05882353
 0.05882353 0.05882353 0.05882353 0.05882353 0.05882353 0.05882353
 0.05882353 0.05882353 0.05882353 0.05882353 0.05882353]

infograph train (900, 3, 32, 32)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16] [ 60  25  40 120 120  25  60  40 120  25  10  80  25  10  10 120  10] [0.06666667 0.02777778 0.04444444 0.13333333 0.13333333 0.02777778
 0.06666667 0.04444444 0.13333333 0.02777778 0.01111111 0.08888889
 0.02777778 0.01111111 0.01111111 0.

In [5]:
analyze('covid')

1 train (800, 17)
[0 1] [ 59 741] [0.07375 0.92625]
1 test (2000, 17)
[0 1] [ 160 1840] [0.08 0.92]

2 train (800, 17)
[0 1] [ 99 701] [0.12375 0.87625]
2 test (2000, 17)
[0 1] [ 259 1741] [0.1295 0.8705]

3 train (800, 17)
[0 1] [110 690] [0.1375 0.8625]
3 test (2000, 17)
[0 1] [ 277 1723] [0.1385 0.8615]

4 train (800, 17)
[0 1] [ 84 716] [0.105 0.895]
4 test (2000, 17)
[0 1] [ 216 1784] [0.108 0.892]

5 train (800, 17)
[0 1] [ 39 761] [0.04875 0.95125]
5 test (2000, 17)
[0 1] [  78 1922] [0.039 0.961]



In [9]:
(59) / (59 + 741)

100.0

In [6]:
sum([800-59, 800-99, 800-110, 800-84, 800-39]) / (800*5)

0.90225

In [7]:
sum([800-59, 800-99, 800-110, 800-84, 800-39])

3609